name: Money4Mobs
<<<<<<< HEAD
version: 1.4.1
=======
version: 1.5.0
>>>>>>> 8155c2b4325e78607f9eda6783a63fe15bdbbde9
author: Latch
main: Latch.Money4Mobs.Money4Mobs
api-version: 1.16
softdepend: [Vault]
commands:
  mk:
    description: Mob Killer
    usage: /mk