name: Money4Mobs
version: 1.6.6.2-DEV-Spawn-Logic-Wolf-Reward-Money
author: Latch
main: Latch.Money4Mobs.Money4Mobs
api-version: 1.17
softdepend: [Vault]
commands:
  mk:
    description: Mob Killer
    usage: /mk